/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ailatrieuphu;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author NhuTam
 */
public class GiaoDienGame extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienGame
     */
    private int dungkhong;
    private int socauhoi;
    private final int k;
    private int n;
    private Vector v=new Vector();
    private String sau;
    private Clock cl = null;
   
    
    
    public GiaoDienGame() {
        initComponents();
        cl = new Clock(jLabel4);
               cl.reset();
              cl.start();
              if (cl.i==0)
              {
                  new BaoDiem(this, true, sau).setVisible(true);
              }
        socauhoi=1;
        jLabel3.setText("$1");
        sau=jLabel3.getText();
        Random rd=new Random();
        Dulieu dl=new Dulieu();
        k=rd.nextInt(17);
        dl.CauHoi(k);
        dungkhong=dl.dung;
        jLabel2.setText("<html>Câu hỏi số "+socauhoi+" :"+ dl.quest[0]+"</html>");
        jToggleButton1.setText(dl.quest[1]);
        jToggleButton2.setText(dl.quest[2]);
        jToggleButton3.setText(dl.quest[3]);
        jToggleButton4.setText(dl.quest[4]);
        
        
    }
    public void chuyenCauHoi(){
        jToggleButton1.setSelected(false);
        jToggleButton2.setSelected(false);
        jToggleButton3.setSelected(false);
        jToggleButton4.setSelected(false);
        jToggleButton1.setBackground(null);
        jToggleButton2.setBackground(null);
        jToggleButton3.setBackground(null);
        jToggleButton4.setBackground(null);
        socauhoi++;
        if (socauhoi==2) {
            jLabel3.setText("$1000");
        }
        if (socauhoi==3) {
            jLabel3.setText("$2000");
        }
        if (socauhoi==4) {
            jLabel3.setText("$3000");
        }
        if (socauhoi==5) {
            jLabel3.setText("$5000");
        }
        if (socauhoi==6) {
            jLabel3.setText("$10000");
        }
        if (socauhoi==7) {
            jLabel3.setText("$20000");
        }
        if (socauhoi==8) {
            jLabel3.setText("$30000");
        }
        if (socauhoi==9) {
            jLabel3.setText("$60000");
        }
        if (socauhoi==10) {
            jLabel3.setText("$90000");
        }
        if (socauhoi==11) {
            jLabel3.setText("$150000");
        }
        if (socauhoi==12) {
            jLabel3.setText("$250000");
        }
        if (socauhoi==13) {
            jLabel3.setText("$350000");
        }
        if (socauhoi==14) {
            jLabel3.setText("$500000");
        }
        if (socauhoi==15) {
            jLabel3.setText("$800000");
        }
        if (socauhoi==16) {
            jLabel3.setText("$1200000");
            this.setVisible(false);
            new ChucMung().setVisible(true);
            
        }
        sau=jLabel3.getText();
        
        v.add(k);   
        Random rd=new Random();
        Dulieu dl=new Dulieu();
        do{
            n=rd.nextInt(17);
            
        }
        while(v.contains(n));
        //System.out.print(n + " ");
        v.add(n);
        dl.CauHoi(n);
        dungkhong=dl.dung;
        jLabel2.setText("<html>Câu hỏi số "+socauhoi+" :"+ dl.quest[0]+"</html>");
        jToggleButton1.setText(dl.quest[1]);
        jToggleButton2.setText(dl.quest[2]);
        jToggleButton3.setText(dl.quest[3]);
        jToggleButton4.setText(dl.quest[4]);
    }
    public void hienDiem(){
        BaoDiem tb =new BaoDiem(this,true,sau);
        tb.setVisible(true);
        if (tb.getReturnStatus()==1||tb.getReturnStatus()==0)
            {
                this.setVisible(false);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/ailatrieuphu/Image/nen1.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame2"); // NOI18N
        setPreferredSize(new java.awt.Dimension(480, 680));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/anhnen.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(102, 0, 0));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/iconA.jpg"))); // NOI18N
        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(102, 0, 0));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/Icon B.png"))); // NOI18N
        jToggleButton2.setText("jToggleButton1");
        jToggleButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(102, 0, 0));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/IconC.png"))); // NOI18N
        jToggleButton3.setText("jToggleButton1");
        jToggleButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(102, 0, 0));
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/IconD.png"))); // NOI18N
        jToggleButton4.setText("jToggleButton1");
        jToggleButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Câu hỏi số ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1300");
        jLabel3.setToolTipText("Điểm");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/5050.png"))); // NOI18N
        jButton1.setToolTipText("Trợ giúp 50/50");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/phone.png"))); // NOI18N
        jButton2.setToolTipText("Gọi điện cho chuyên gia!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/khangia.png"))); // NOI18N
        jButton3.setToolTipText("Hỏi khán giả trường quay!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/reload.png"))); // NOI18N
        jButton4.setToolTipText("Đổi câu hỏi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/exit.png"))); // NOI18N
        jButton5.setToolTipText("Dừng cuộc chơi !");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("10:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap())))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LuaChonHayKhong lc =new LuaChonHayKhong(this, true, "Bạn muốn dùng trợ giúp 50:50?");
        lc.setVisible(true);
        if (lc.getReturnStatus()==1){
            if (dungkhong==1)
            {
                jToggleButton2.setText(null);
                jToggleButton4.setText(null);
            }
            if (dungkhong==2)
            {
                jToggleButton1.setText(null);
                jToggleButton4.setText(null);
            }
            if (dungkhong==3)
            {
                jToggleButton1.setText(null);
                jToggleButton3.setText(null);
            }
            if (dungkhong==4)
            {
                jToggleButton2.setText(null);
                jToggleButton1.setText(null);
            }
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/not5050.png")));
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        jToggleButton2.setSelected(false);
        jToggleButton3.setSelected(false);
        jToggleButton4.setSelected(false);
        NewOkCancelDialog kt =new NewOkCancelDialog(this, true);
        kt.setVisible(true);
        if (kt.getReturnStatus()==0)
        {
            jToggleButton1.setSelected(false);
        }
        if (kt.getReturnStatus()==1){
            if (dungkhong==1){
                jToggleButton1.setBackground(Color.green);
                
                chuyenCauHoi();
            }
            else if(dungkhong==2){
                jToggleButton1.setBackground(Color.gray);
                jToggleButton2.setBackground(Color.green);
                hienDiem();
                
            }
            else if(dungkhong==3){
                jToggleButton1.setBackground(Color.gray);
                jToggleButton3.setBackground(Color.green);
                hienDiem();
                
            }
            else if(dungkhong==4){
                jToggleButton1.setBackground(Color.gray);
                jToggleButton4.setBackground(Color.green);
                hienDiem();
            }
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        jToggleButton1.setSelected(false);
        jToggleButton3.setSelected(false);
        jToggleButton4.setSelected(false);
        NewOkCancelDialog kt =new NewOkCancelDialog(this, true);
        kt.setVisible(true);
        if (kt.getReturnStatus()==0)
        {
            jToggleButton2.setSelected(false);
        }
        if (kt.getReturnStatus()==1){
            if (dungkhong==2){
                jToggleButton2.setBackground(Color.green);
                
                chuyenCauHoi();
            }
            else if(dungkhong==1){
                jToggleButton2.setBackground(Color.gray);
                jToggleButton1.setBackground(Color.green);
                hienDiem();
            }
            else if(dungkhong==3){
                jToggleButton2.setBackground(Color.gray);
                jToggleButton3.setBackground(Color.green);
                hienDiem();
            }
            else if(dungkhong==4){
                jToggleButton2.setBackground(Color.gray);
                jToggleButton4.setBackground(Color.green);
                hienDiem();
            }
        }
        
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        jToggleButton2.setSelected(false);
        jToggleButton1.setSelected(false);
        jToggleButton4.setSelected(false);
        NewOkCancelDialog kt =new NewOkCancelDialog(this, true);
        kt.setVisible(true);
        if (kt.getReturnStatus()==0)
        {
            jToggleButton3.setSelected(false);
        }
        if (kt.getReturnStatus()==1){
            if (dungkhong==3){
                jToggleButton3.setBackground(Color.green);
                chuyenCauHoi();
            }
            else if(dungkhong==2){
                jToggleButton3.setBackground(Color.gray);
                jToggleButton2.setBackground(Color.green);
                hienDiem();
            }
            else if(dungkhong==1){
                jToggleButton3.setBackground(Color.gray);
                jToggleButton1.setBackground(Color.green);
                hienDiem();
                
            }
            else if(dungkhong==4){
                jToggleButton3.setBackground(Color.gray);
                jToggleButton4.setBackground(Color.green);
                hienDiem();
            }
        }
        
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        jToggleButton2.setSelected(false);
        jToggleButton1.setSelected(false);
        jToggleButton3.setSelected(false);
        NewOkCancelDialog kt =new NewOkCancelDialog(this, true);
        kt.setVisible(true);
        if (kt.getReturnStatus()==0)
        {
            jToggleButton4.setSelected(false);
        }
        if (kt.getReturnStatus()==1){
            if (dungkhong==4){
                jToggleButton4.setBackground(Color.green);
                
                chuyenCauHoi();
            }
            else if(dungkhong==2){
                jToggleButton4.setBackground(Color.gray);
                jToggleButton2.setBackground(Color.green);
                hienDiem();
            }
            else if(dungkhong==3){
                jToggleButton4.setBackground(Color.gray);
                jToggleButton3.setBackground(Color.green);
                hienDiem();
            }
            else if(dungkhong==1){
                jToggleButton4.setBackground(Color.gray);
                jToggleButton1.setBackground(Color.green);
                hienDiem();
            }
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         LuaChonHayKhong lc =new LuaChonHayKhong(this, true, "Bạn muốn dừng cuộc chơi");
        lc.setVisible(true);
        if (lc.getReturnStatus()==1){
        new BaoDiem(this, true, sau).setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LuaChonHayKhong lc =new LuaChonHayKhong(this, true, "Bạn muốn đổi câu hỏi?");
        lc.setVisible(true);
        if (lc.getReturnStatus()==1)
        {
            Random rd=new Random();
        Dulieu dl=new Dulieu();
        do{
            n=rd.nextInt(17);
            
        }
        while(v.contains(n));
        //System.out.print(n + " ");
        v.add(n);
        dl.CauHoi(n);
        dungkhong=dl.dung;
        jLabel2.setText("<html>Câu hỏi số "+socauhoi+" :"+ dl.quest[0]+"</html>");
        jToggleButton1.setText(dl.quest[1]);
        jToggleButton2.setText(dl.quest[2]);
        jToggleButton3.setText(dl.quest[3]);
        jToggleButton4.setText(dl.quest[4]);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/notreload.png")));
        jButton4.setEnabled(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LuaChonHayKhong lc =new LuaChonHayKhong(this, true, "Bạn muốn hỏi ý kiến khán giả?");
        lc.setVisible(true);
        if (lc.getReturnStatus()==1)
        {
            new HoiKhanGia(this, true).setVisible(true);
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/notkhangia.png")));
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LuaChonHayKhong lc =new LuaChonHayKhong(this, true, "Bạn muốn gọi điện cho chuyên gia?");
        lc.setVisible(true);
        if (lc.getReturnStatus()==1)
        {
            HoiChuyenGia hoi=new HoiChuyenGia(this, true);
            hoi.setVisible(true);
            if (hoi.getReturnStatus()==1)
            {
                    if (dungkhong==1)
                {
                   PhuongAnCuaChuyenGia pa=new PhuongAnCuaChuyenGia(this, true, "Theo tôi là phương án A !");
                   pa.setVisible(true);
                }
                if (dungkhong==2)
                {
                   PhuongAnCuaChuyenGia pa=new PhuongAnCuaChuyenGia(this, true, "Theo tôi là phương án B !");
                   pa.setVisible(true);
                }
                if (dungkhong==3)
                {
                   PhuongAnCuaChuyenGia pa=new PhuongAnCuaChuyenGia(this, true, "Theo tôi là phương án C !");
                   pa.setVisible(true);
                }
                if (dungkhong==4)
                {
                   PhuongAnCuaChuyenGia pa=new PhuongAnCuaChuyenGia(this, true, "Theo tôi là phương án D !");
                   pa.setVisible(true);
                }
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Image/notphone.png")));
                jButton2.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public class ToDo  {
  Timer timer;

  public ToDo ( int seconds )   {
    timer = new Timer (  ) ;
    timer.schedule ( new ToDoTask (  ) , seconds*1000 ) ;
  }


  class ToDoTask extends TimerTask  {
    public void run (  )   {
        hienDiem();
      timer.cancel (  ) ; //Terminate the thread
    }
  }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienGame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
